---
- src: https://github.com/bossjones/boss-ansible-role-fact
- src: https://github.com/bossjones/boss-ansible-role-environment
- src: https://github.com/bossjones/boss-ansible-role-core
- src: https://github.com/bossjones/boss-ansible-role-docker
- src: https://github.com/bossjones/boss-ansible-role-dnsmasq
