---

# no_log: true

- hosts: etckeeper_servers
  gather_facts: True
  become: yes
  become_method: sudo
  tags:
    - etckeeper
  roles:
    - role: boss-ansible-role-bootstrap
    - role: boss-ansible-role-core
    - role: boss-ansible-role-fact
    - role: boss-ansible-role-environment
    - role: ../
      boss__etckeeper__vcs_user: 'jarvis'
      boss__etckeeper__vcs_email: 'jarvis@theblacktonystark.com'
